language: python
notifications:
  email: false
sudo: false
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- coverage run -m pytest
deploy:
  provider: pypi
  user: blackcat
  true:
    python: 3.6
    tags: true
    branch: master
  password:
    secure: IWfmM4Js8j+TBfUuf8qFtaFT5fEE7w5QtNVGNNufOZCs9WF59O05a68GPm0nKANIfvJbTnIdXt42PQyVFDUyk9cjtbcqWL6lwD4vh7ikuxkg8c6sWt1F5uNGRPab7EgMSmbc2oK+pHP7Kybjbq1SK/vAETjVw9XF/+jaha3CeBmErFJXFlQGYjLLGaIRHO7IBGf+knfxKJfeAfIcUF8TDnsfx5NYLVkCGzmEuRNKo7Ozb5DdySGCmwciv49KJzw+F2Xz+Stq7Qh2/xMoXVfIuPdsYU2HWhUeA0MsAe0KNBwAVVMdBVdLV9p/36LTuBwBmM9MXF/gbPJxb2JFrN3jeJfmTQHFgKwe4vAM4NFeArJ7kCGd+Fis+sA2KgtLez44eG8sLqF6780YuFaCbe08OAQN/IUS/bwUl19oKkG5IUVjFd3nBhDZQ0C1hKJYtD5nWAF+cC16DpMVXEu2bjr2q1lXFbJyE6r+BvG0DTWRTIW69MasnYg8qcI+r81O9ycqRIhQYfxzXjKwZwWOWKG3N6mHvHpjKxAkAcuN1jRajJr4jcyFTJj4+gFT2HnzZTeZsfL5VkaPuDSSk2jIdw4K0yfiGUunGsP+fiEIFefwdoxqgydMXhxg5bbDWvTuy/MB7QCQCZ/MEJm7w6BnwLaL2+lnt2IPWq25F01Tx+NUfuU=
after_success: coveralls
