language: python
notifications:
  email: false
sudo: false
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- coverage run -m pytest
deploy:
  provider: pypi
  user: blackcat
  on:
    python: 3.6
    tags: true
    branch: master
  password:
    secure: RnjTjyVt1sIPNBr5UfpAF/mK5DmOjJ1LbfrgIFsZhhVW3jNtohKk3NRiV9s8QTksUUH8Q5S8MQ0/KeK55gaUBkABmssfDmr/fZY07ejQQs6t5vxQHD93u/X6fXv+FCV9PLNNVnB8/7t1L3AMorAC5W4QvvzKNuN4GRiaOoxn9Dps57g09tCeNMjlv7WEmqvti/EaJu6vCk3STF+nO5HiaJJZ1zZzD2h52Yn7m5skVTA7uHm20If0wATYhi54NaeCi7WJXTdIqCa8HBAgavAaVvFNJBCk35dHg0/0M/hWlnFrq2v5G7QKPC7eFBGWSJl2BfZPwx6c39QkBH1fUzxy/lDFgTesL2vSGAHYZQzWJqBVqzJMcLR3s4z2jek1pR5UYFZAuZ1955bpZMfRSRfdku/LhKUL+BoWPv/rmkxL/fBPlMJKrwEhrYIVhkSxa0NNs+TFcOkMCZdgj7DWjPa/JuJFOHvlIbeaX3jRDtkV5P4Jekwml7ERtE7zd4AEGMoY0eF5Hi39kG0EhA5IUjyRjRRYp5hkeYgg4q9MABktOa0BZU54Aph1I8kbDFX5dhe1Gyku/2Rops6dF7ef4xVh+BcjB7Bn6HyBDbzl2NE7w1ZzkyKyECWWP8zIW77TNNF4RVvsyvzfV1Z39uqMJIjsk6fes+XxPkwrbqRrzj5UpoM=
    
after_success: 
  coveralls
